version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Karachi"
    open-pull-requests-limit: 5

  - package-ecosystem: "gradle"
    directory: "/NexusNovaAndroid"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
      timezone: "Asia/Karachi"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "Asia/Karachi"
    open-pull-requests-limit: 5
