const {onRequest}=require('firebase-functions/v2/https');

const DUFFEL_API='https://api.duffel.com';
const DEFAULT_AMADEUS='https://api.amadeus.com';
const SEARCH_TIMEOUT_MS=24000;
const TRACK_TIMEOUT_MS=12000;
const rateBuckets=new Map();

function cleanText(value,label,max=80){const text=String(value??'').trim();if(!text||text.length>max)throw new Error(`Invalid ${label}.`);return text;}
function cleanDate(value,label){const text=cleanText(value,label,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(text))throw new Error(`Invalid ${label}.`);if(!Number.isFinite(Date.parse(`${text}T00:00:00Z`)))throw new Error(`Invalid ${label}.`);return text;}
function cleanAdults(value){const n=Math.floor(Number(value));if(!Number.isInteger(n)||n<1||n>9)throw new Error('Adults must be between 1 and 9.');return n;}
function cleanChildren(value){const n=Math.floor(Number(value??0));if(!Number.isInteger(n)||n<0||n>9)throw new Error('Children must be between 0 and 9.');return n;}
function cleanCabin(value){const raw=String(value||'economy').toLowerCase();return new Set(['economy','premium_economy','business','first']).has(raw)?raw:'economy';}
function cleanCurrency(value){const code=String(value||'USD').toUpperCase();return /^[A-Z]{3}$/.test(code)?code:'USD';}
async function fetchJson(url,options={},timeoutMs=SEARCH_TIMEOUT_MS){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(url,{...options,signal:controller.signal});const text=await response.text();let data=null;try{data=text?JSON.parse(text):null}catch{}if(!response.ok){const detail=data?.errors?.[0]?.detail||data?.error_description||data?.error?.message||`HTTP ${response.status}`;throw new Error(String(detail).slice(0,240));}return data;}finally{clearTimeout(timer);}}
function duffelToken(){return String(process.env.DUFFEL_ACCESS_TOKEN||'').trim();}
function amadeusCreds(){return{id:String(process.env.AMADEUS_CLIENT_ID||'').trim(),secret:String(process.env.AMADEUS_CLIENT_SECRET||'').trim(),base:String(process.env.AMADEUS_API_BASE||DEFAULT_AMADEUS).trim().replace(/\/+$/,'')};}
function flightAwareToken(){return String(process.env.FLIGHTAWARE_API_TOKEN||'').trim();}
async function duffel(path,options={}){const token=duffelToken();if(!token)throw new Error('Duffel provider is not configured.');return fetchJson(`${DUFFEL_API}${path}`,{...options,headers:{Accept:'application/json','Content-Type':'application/json','Duffel-Version':'v2',Authorization:`Bearer ${token}`,...(options.headers||{})}});}
let amadeusToken={value:'',expiresAt:0};
async function amadeus(path){const {id,secret,base}=amadeusCreds();if(!id||!secret)throw new Error('Amadeus provider is not configured.');if(!amadeusToken.value||Date.now()>=amadeusToken.expiresAt-60000){const body=new URLSearchParams({grant_type:'client_credentials',client_id:id,client_secret:secret});const auth=await fetchJson(`${base}/v1/security/oauth2/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body.toString()},12000);if(!auth?.access_token)throw new Error('Amadeus authentication failed.');amadeusToken={value:String(auth.access_token),expiresAt:Date.now()+Math.max(300,Number(auth.expires_in)||1200)*1000};}return fetchJson(`${base}${path}`,{headers:{Accept:'application/json',Authorization:`Bearer ${amadeusToken.value}`}});}
function isoMinutes(v){const m=/^P(?:(\d+)D)?T?(?:(\d+)H)?(?:(\d+)M)?$/i.exec(String(v||''));return m?(Number(m[1]||0)*1440+Number(m[2]||0)*60+Number(m[3]||0)):null;}
function diffMinutes(a,b){const x=Date.parse(a),y=Date.parse(b);return Number.isFinite(x)&&Number.isFinite(y)&&y>=x?Math.round((y-x)/60000):null;}
async function resolveDuffelPlace(raw){if(/^[A-Za-z]{3}$/.test(raw))return String(raw).toUpperCase();const j=await duffel(`/places/suggestions?query=${encodeURIComponent(raw)}`);const item=(j?.data||[]).find(x=>/^[A-Z]{3}$/.test(String(x?.iata_code||'').toUpperCase()));if(!item)throw new Error(`Airport/city not found: ${raw}`);return String(item.iata_code).toUpperCase();}
async function resolveAmadeusPlace(raw){if(/^[A-Za-z]{3}$/.test(raw))return String(raw).toUpperCase();const q=new URLSearchParams({subType:'CITY,AIRPORT',keyword:raw,'page[limit]':'8',view:'LIGHT'});const j=await amadeus(`/v1/reference-data/locations?${q.toString()}`);const item=(j?.data||[]).find(x=>/^[A-Z]{3}$/.test(String(x?.iataCode||'').toUpperCase()));if(!item)throw new Error(`Airport/city not found: ${raw}`);return String(item.iataCode).toUpperCase();}
function duffelOffers(json,origin,destination){return (json?.data?.offers||[]).map(o=>{const amount=Number(o?.total_amount),currency=String(o?.total_currency||'').toUpperCase(),slices=Array.isArray(o?.slices)?o.slices:[],segments=slices.flatMap(s=>Array.isArray(s?.segments)?s.segments:[]),first=segments[0],last=segments[segments.length-1];if(!(amount>0)||!/^[A-Z]{3}$/.test(currency)||!first||!last)return null;const carriers=[...new Set(segments.map(s=>s?.operating_carrier?.name||s?.marketing_carrier?.name).filter(Boolean))];const duration=slices.reduce((n,s)=>n+(isoMinutes(s?.duration)||0),0)||diffMinutes(first.departing_at,last.arriving_at);return{airline:carriers[0]||'Airline unavailable',airlines:carriers,flightNumber:segments[0]?.marketing_carrier_flight_number||segments[0]?.operating_carrier_flight_number||'',origin,destination,departure:first.departing_at||'',arrival:last.arriving_at||'',duration:duration?`${Math.floor(duration/60)}h ${duration%60}m`:'',stops:Math.max(0,segments.length-1),aircraft:[...new Set(segments.map(s=>s?.aircraft?.name||s?.aircraft?.iata_code).filter(Boolean))].join(', ')||'',price:{amount,currency},provider:'Duffel',providerOfferId:String(o?.id||''),live:true};}).filter(Boolean);}
async function searchDuffel(c){const [o,d]=await Promise.all([resolveDuffelPlace(c.origin),resolveDuffelPlace(c.destination)]);const slices=[{origin:o,destination:d,departure_date:c.departureDate}];if(c.returnDate)slices.push({origin:d,destination:o,departure_date:c.returnDate});const passengers=[...Array(c.adults)].map(()=>({type:'adult'})).concat([...Array(c.children)].map(()=>({type:'child'})));const j=await duffel('/air/offer_requests?return_offers=true&supplier_timeout=12000',{method:'POST',body:JSON.stringify({data:{slices,passengers,cabin_class:c.cabin}})});return duffelOffers(j,o,d);}
function amadeusOffers(j){return (j?.data||[]).map(o=>{const amount=Number(o?.price?.grandTotal||o?.price?.total),currency=String(o?.price?.currency||'').toUpperCase(),its=Array.isArray(o?.itineraries)?o.itineraries:[],segs=its.flatMap(i=>Array.isArray(i?.segments)?i.segments:[]),first=segs[0],last=segs[segs.length-1];if(!(amount>0)||!/^[A-Z]{3}$/.test(currency)||!first||!last)return null;const codes=[...new Set(segs.map(s=>s?.operating?.carrierCode||s?.carrierCode).filter(Boolean))];const airlines=codes.map(code=>String(j?.dictionaries?.carriers?.[code]||code));const duration=its.reduce((n,i)=>n+(isoMinutes(i?.duration)||0),0)||diffMinutes(first?.departure?.at,last?.arrival?.at);return{airline:airlines[0]||'Airline unavailable',airlines,flightNumber:first?.carrierCode&&first?.number?`${first.carrierCode}${first.number}`:'',origin:first?.departure?.iataCode||'',destination:last?.arrival?.iataCode||'',departure:first?.departure?.at||'',arrival:last?.arrival?.at||'',duration:duration?`${Math.floor(duration/60)}h ${duration%60}m`:'',stops:Math.max(0,segs.length-1),aircraft:[...new Set(segs.map(s=>s?.aircraft?.code).filter(Boolean))].join(', ')||'',price:{amount,currency},provider:'Amadeus',providerOfferId:String(o?.id||''),live:true};}).filter(Boolean);}
async function searchAmadeus(c){const [o,d]=await Promise.all([resolveAmadeusPlace(c.origin),resolveAmadeusPlace(c.destination)]);const p=new URLSearchParams({originLocationCode:o,destinationLocationCode:d,departureDate:c.departureDate,adults:String(c.adults),children:String(c.children),travelClass:c.cabin.toUpperCase(),currencyCode:c.currency,max:'36'});if(c.returnDate)p.set('returnDate',c.returnDate);return amadeus(`/v2/shopping/flight-offers?${p.toString()}`).then(amadeusOffers);}
function allow(ip){const now=Date.now(),windowMs=60000,max=30;const arr=(rateBuckets.get(ip)||[]).filter(t=>now-t<windowMs);if(arr.length>=max)return false;arr.push(now);rateBuckets.set(ip,arr);if(rateBuckets.size>2000){for(const [k,v] of rateBuckets)if(v.every(t=>now-t>=windowMs))rateBuckets.delete(k);}return true;}
function authGate(req,res){const auth=String(req.headers.authorization||'');const key=String(process.env.NEXUS_TRAVEL_API_KEY||'').trim();if(key&&auth!==`Bearer ${key}`){res.status(401).json({ok:false,message:'Travel API authentication required.'});return false;}return true;}
async function handleSearch(req,res){const origin=cleanText(req.body?.from??req.body?.origin,'origin');const destination=cleanText(req.body?.to??req.body?.destination,'destination');const departureDate=cleanDate(req.body?.departureDate??req.body?.departure,'departure date');const returnDate=String(req.body?.returnDate||'').trim()?cleanDate(req.body.returnDate,'return date'):'';if(returnDate&&returnDate<departureDate)throw new Error('Return date must be after departure date.');const c={origin,destination,departureDate,returnDate,adults:cleanAdults(req.body?.adults),children:cleanChildren(req.body?.children),cabin:cleanCabin(req.body?.cabin),currency:cleanCurrency(req.body?.currency)};const configured={duffel:Boolean(duffelToken()),amadeus:Boolean(amadeusCreds().id&&amadeusCreds().secret)};const jobs=[];if(configured.duffel)jobs.push(searchDuffel(c));if(configured.amadeus)jobs.push(searchAmadeus(c));if(!jobs.length){res.status(503).json({ok:false,reason:'providers-not-configured',message:'No secure flight provider is configured on the backend.',providers:configured,results:[]});return;}const settled=await Promise.allSettled(jobs);const results=settled.flatMap(x=>x.status==='fulfilled'?x.value:[]).sort((a,b)=>(a.price?.amount??Number.MAX_VALUE)-(b.price?.amount??Number.MAX_VALUE)).slice(0,36);const providerErrors=settled.filter(x=>x.status==='rejected').map(x=>String(x.reason?.message||'Provider search failed').slice(0,240));res.json({ok:true,live:true,searchedAt:Date.now(),providers:configured,providerErrors,results});}
async function handleTrack(req,res){const token=flightAwareToken();if(!token){res.status(503).json({ok:false,available:false,reason:'provider-not-configured',message:'Live aircraft tracking is not configured on the secure backend.'});return;}const ident=cleanText(req.query.flight,'flight number',24);const base='https://aeroapi.flightaware.com/aeroapi';const flights=await fetchJson(`${base}/flights/${encodeURIComponent(ident)}?max_pages=1`,{headers:{Accept:'application/json','x-apikey':token}},TRACK_TIMEOUT_MS);const f=(flights?.flights||[])[0];if(!f){res.status(404).json({ok:false,available:false,message:'Flight not found.'});return;}let pos=null;try{pos=await fetchJson(`${base}/flights/${encodeURIComponent(f.fa_flight_id)}/position`,{headers:{Accept:'application/json','x-apikey':token}},TRACK_TIMEOUT_MS);}catch{}
const out={id:f.fa_flight_id||'',ident:f.ident||ident,status:f.status||f.flight_status||'',origin:f.origin?.name||f.origin?.code||'',destination:f.destination?.name||f.destination?.code||'',departure:f.scheduled_off||f.estimated_off||f.actual_off||'',arrival:f.scheduled_on||f.estimated_on||f.actual_on||'',eta:f.estimated_on||f.scheduled_on||'',delayMinutes:null,latitude:pos?.latitude??null,longitude:pos?.longitude??null,heading:pos?.heading??null,altitude:pos?.altitude??null,groundspeed:pos?.groundspeed??null,route:f.route||[]};res.json({ok:true,available:true,live:true,flight:out,provider:'FlightAware AeroAPI',fetchedAt:Date.now()});}
const travelApi=onRequest({cors:true,timeoutSeconds:60,memory:'512MiB'},async(req,res)=>{try{res.set('Cache-Control','no-store');const ip=String(req.headers['x-forwarded-for']||req.ip||'unknown').split(',')[0].trim();if(!allow(ip)){res.status(429).json({ok:false,message:'Too many travel requests. Please retry shortly.'});return;}if(!authGate(req,res))return;const path=String(req.path||'/').replace(/^\/api\/travel/,'').replace(/^\/+/,'');if(req.method==='POST'&&['flights/search','search/flights'].includes(path)){await handleSearch(req,res);return;}if(req.method==='GET'&&['flights/track','track'].includes(path)){await handleTrack(req,res);return;}if(req.method==='POST'&&['buses/search','trains/search','hotels/search'].includes(path)){res.status(503).json({ok:false,available:false,reason:'provider-not-configured',message:'This module has no configured live provider in NexusNova yet. No schedules, rooms or prices are fabricated.',results:[]});return;}res.status(404).json({ok:false,message:'Unknown Travel API route.'});}catch(error){console.error('[Travel API]',error);res.status(400).json({ok:false,message:String(error?.message||'Travel request failed.').slice(0,240),results:[]});}});

exports.travelApi=travelApi;
