const test=require('node:test');
const assert=require('node:assert/strict');
const {FlightAPIAdapter,createFlightApiProvider,normalizeItineraryRows,normalizeTrackingRows}=require('./flightapi-provider');
const {DuffelStaysAdapter,createDuffelStaysProvider,validateBookingInput}=require('./duffel-stays-provider');
const {analyzeHotelValue}=require('./hotel-value');

test('FlightAPI factory fails closed without a secret',()=>{assert.equal(createFlightApiProvider({}),null);assert.equal(new FlightAPIAdapter('').available,false)});
test('FlightAPI normalizes the documented relational response shape',()=>{const rows=normalizeItineraryRows({itineraries:[{id:'it1',leg_ids:['leg1'],pricing_options:[{price:{amount:'125.50',currency:'USD',last_updated:'2026-09-14T10:00:00Z'},items:[{url:'https://provider.example/book'}]}]}],legs:[{id:'leg1',segment_ids:['seg1'],departure:'2026-10-01T10:00:00Z',arrival:'2026-10-01T12:00:00Z',duration:120,origin:{iata:'KHI'},destination:{iata:'DXB'}}],segments:[{id:'seg1',departure:'2026-10-01T10:00:00Z',arrival:'2026-10-01T12:00:00Z',origin:{iata:'KHI'},destination:{iata:'DXB'},marketing_flight_number:'XY123',marketing_carrier_id:'c1'}],carriers:[{id:'c1',name:'Example Air'}]});assert.equal(rows.length,1);assert.equal(rows[0].provider,'FlightAPI');assert.equal(rows[0].price,125.5);assert.equal(rows[0].currency,'USD');assert.equal(rows[0].originCode,'KHI');assert.equal(rows[0].destinationCode,'DXB');assert.equal(rows[0].flightNumber,'XY123');assert.equal(rows[0].airline,'Example Air');assert.equal(rows[0].durationMinutes,120);assert.equal(rows[0].bookingUrl,'https://provider.example/book')});
test('FlightAPI tracking normalization preserves provider status facts',()=>{const rows=normalizeTrackingRows([{FlightNumber:'PK301',Airline:'PK',Status:'Landed',DepartureTime:'2026-09-14T12:00:00Z',ArrivalTime:'2026-09-14T14:00:00Z'}]);assert.deepEqual(rows[0],{id:'PK301-0',airline:'PK',flightNumber:'PK301',status:'Landed',operatedBy:'',departure:'2026-09-14T12:00:00Z',arrival:'2026-09-14T14:00:00Z',liveMode:true,provider:'FlightAPI'})});
test('Duffel Stays factory fails closed without access',()=>{assert.equal(createDuffelStaysProvider({}),null);assert.equal(new DuffelStaysAdapter('').available,false)});
test('Duffel Stays booking validates guests and uses quote id',()=>{const v=validateBookingInput({quoteId:'quo_123',guests:[{givenName:'A',familyName:'B',email:'a@example.com',phone:'+1'}]});assert.equal(v.quoteId,'quo_123');assert.deepEqual(v.guests[0],{given_name:'A',family_name:'B',email:'a@example.com',phone_number:'+1'})});
test('Duffel Stays booking rejects missing guests',()=>{assert.throws(()=>validateBookingInput({quoteId:'quo_123',guests:[]}),/lead guest/)});
test('Hotel value explains only supplied facts',()=>{const a=analyzeHotelValue({price:80,reviewScore:9,reviewCount:250,amenities:['WiFi','Breakfast'],rate:{name:'Deluxe King',meal:'Breakfast',cancellation:'Free cancellation'}},[{price:80},{price:110},{price:130}]);assert.equal(a.status,'complete');assert.match(a.title,/Good value/);assert(a.reasons.some(x=>/lowest supplied price/.test(x)));assert(a.reasons.some(x=>/review score/.test(x)));});
test('Hotel value refuses arbitrary score with insufficient facts',()=>{const a=analyzeHotelValue({},[]);assert.equal(a.status,'insufficient');assert.equal(a.title,'Not enough data to determine value.')});
