const {onRequest}=require('firebase-functions/v2/https');
const {getAuth}=require('firebase-admin/auth');
const {getFirestore,FieldValue}=require('firebase-admin/firestore');
const {ProviderError,createFlightProvider,keylessAirportSearch}=require('./travel-provider');
const {createFlightApiProvider,FlightApiError}=require('./flightapi-provider');
const {createDuffelStaysProvider,StaysError}=require('./duffel-stays-provider');
const {buildCapabilityMatrix,BOOKING_STATES,PAYMENT_STATES,TRANSITIONS}=require('./travel-contracts');
const crypto=require('node:crypto');

const MAX_BODY=8192,MAX_Q=120,WINDOW_MS=60_000,MAX_REQUESTS_PER_WINDOW=90;
const db=getFirestore();
const rateBuckets=new Map();

function json(res,status,payload){res.status(status).set('Cache-Control','no-store').json(payload)}
function requestId(req){const incoming=String(req.get?.('X-Request-Id')||'').trim();return /^[A-Za-z0-9._:-]{8,120}$/.test(incoming)?incoming:`travel_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,10)}`}
function clientKey(req){const forwarded=String(req.get?.('x-forwarded-for')||'').split(',')[0].trim();return (forwarded||String(req.ip||'unknown')).slice(0,80)}
function allowedOrigin(req){const configured=String(process.env.TRAVEL_ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);const origin=String(req.get?.('origin')||'').trim();if(!origin||configured.includes('*'))return configured.includes('*')?'*':'';return configured.includes(origin)?origin:''}
function security(res,req,id){res.set('X-Request-Id',id).set('X-Content-Type-Options','nosniff').set('Referrer-Policy','no-referrer').set('X-Frame-Options','DENY').set('Permissions-Policy','geolocation=(),camera=(),microphone=()').set('Cross-Origin-Resource-Policy','same-origin');const origin=allowedOrigin(req);if(origin)res.set('Access-Control-Allow-Origin',origin).set('Vary','Origin').set('Access-Control-Allow-Headers','Content-Type, Authorization, X-Request-Id, Idempotency-Key').set('Access-Control-Allow-Methods','GET,POST,OPTIONS')}
function limit(req){const key=clientKey(req),now=Date.now(),bucket=rateBuckets.get(key);if(!bucket||now-bucket.startedAt>=WINDOW_MS){rateBuckets.set(key,{startedAt:now,count:1});return}bucket.count+=1;if(bucket.count>MAX_REQUESTS_PER_WINDOW){const error=new ProviderError('rate_limited','Travel request rate limit reached. Please retry later.',429);error.retryAfter=Math.ceil((bucket.startedAt+WINDOW_MS-now)/1000);throw error}}
function text(v,max=MAX_Q){const s=String(v??'').trim();if(!s||s.length>max)throw new ProviderError('invalid_request','Invalid request.',400);return s}
function code(v){const s=text(v,3).toUpperCase();if(!/^[A-Z]{3}$/.test(s))throw new ProviderError('invalid_request','Invalid airport code.',400);return s}
function date(v){const s=text(v,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw new ProviderError('invalid_request','Invalid date.',400);return s}
function count(v,def,max){const n=v===undefined?def:Number(v);if(!Number.isInteger(n)||n<0||n>max)throw new ProviderError('invalid_request','Invalid count.',400);return n}
function cabin(v){const m={Economy:'economy','Premium Economy':'premium_economy',Business:'business',First:'first',economy:'economy',premium_economy:'premium_economy',business:'business',first:'first'};if(!m[String(v||'')])throw new ProviderError('invalid_request','Invalid cabin class.',400);return m[String(v||'')]}
function readBody(req){const raw=JSON.stringify(req.body||{});if(raw.length>MAX_BODY)throw new ProviderError('invalid_request','Request is too large.',413);return req.body&&typeof req.body==='object'?req.body:{}}
function providers(){return{duffel:createFlightProvider(),flightapi:createFlightApiProvider(),stays:createDuffelStaysProvider()}}
function flightCandidates(){const order=String(process.env.TRAVEL_FLIGHT_PROVIDER_ORDER||'flightapi,duffel').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);const p=providers();return order.map(name=>({name,adapter:p[name]})).filter(x=>x.adapter)}
function handlerError(res,e){if(e?.retryAfter)res.set('Retry-After',String(e.retryAfter));if(e instanceof ProviderError||e instanceof FlightApiError||e instanceof StaysError)return json(res,e.status,{code:e.code,message:e.message});return json(res,500,{code:'internal_error',message:'Travel service could not complete the request.'})}
async function requireUser(req){const auth=String(req.get?.('authorization')||'');const match=auth.match(/^Bearer\s+(.+)$/i);if(!match)throw new ProviderError('unauthenticated','Sign in is required before booking or viewing trips.',401);try{return await getAuth().verifyIdToken(match[1],true)}catch{throw new ProviderError('unauthenticated','Sign in is required before booking or viewing trips.',401)}}
function idemHash(uid,key){return crypto.createHash('sha256').update(`${uid}:${key}`).digest('hex')}
async function reserveBookingAttempt(uid,idempotencyKey,quoteId,provider){const ref=db.collection('travelBookingAttempts').doc(idemHash(uid,idempotencyKey));const existing=await ref.get();if(existing.exists){const value=existing.data()||{};if(value.status==='confirmed')return{ref,existing:value,replay:true};if(value.status==='pending'||value.status==='unknown')throw new StaysError('booking_unknown','This booking attempt already exists and has not reached a safely repeatable state.',409);}
  await ref.set({uid,provider,quoteId,status:'pending',createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});return{ref,existing:null,replay:false}}
async function recordTrip(uid,provider,booking){const safe={provider,type:'hotel',status:'CONFIRMED',bookingId:String(booking?.id||''),reference:String(booking?.reference||booking?.booking_reference||''),createdAt:FieldValue.serverTimestamp()};const tripRef=await db.collection('users').doc(uid).collection('travelTrips').add(safe);return tripRef.id}
async function tryFlights(input){const errors=[];for(const {name,adapter} of flightCandidates())try{return await adapter.searchFlights(input)}catch(e){errors.push({provider:name,code:e.code||'unknown'})}throw new ProviderError('provider_unavailable',`No configured flight provider could complete the request. Tried: ${errors.map(x=>x.provider).join(', ')||'none'}.`,503)}
function hotelCoords(query){const key=String(query||'').trim().toLowerCase();const map={karachi:{lat:24.8607,lng:67.0011},islamabad:{lat:33.6844,lng:73.0479},lahore:{lat:31.5204,lng:74.3587},dubai:{lat:25.2048,lng:55.2708},abudhabi:{lat:24.4539,lng:54.3773},'abu dhabi':{lat:24.4539,lng:55.3773},london:{lat:51.5072,lng:-0.1276},manchester:{lat:53.4808,lng:-2.2426},istanbul:{lat:41.0082,lng:28.9784},ankara:{lat:39.9334,lng:32.8597},riyadh:{lat:24.7136,lng:46.6753},jeddah:{lat:21.4858,lng:39.1925},'new york':{lat:40.7128,lng:-74.006},'los angeles':{lat:34.0522,lng:-118.2437},delhi:{lat:28.6139,lng:77.209},mumbai:{lat:19.076,lng:72.8777}};return map[key]||null}
exports.travelApi=onRequest({timeoutSeconds:60,memory:'256MiB'},async(req,res)=>{const id=requestId(req);security(res,req,id);if(req.method==='OPTIONS')return res.status(204).end();try{
  limit(req);
  const raw=String(req.path||req.url||'').split('?')[0],path=raw.replace(/^\/api\/travel/,'')||'/';
  if(path==='/capabilities'&&req.method==='GET'){const matrix=buildCapabilityMatrix(process.env),p=providers();return json(res,200,{environment:String(process.env.TRAVEL_ENVIRONMENT||'production'),requestId:id,capabilities:matrix,providers:{flightapi:Boolean(p.flightapi),duffel:Boolean(p.duffel),stays:Boolean(p.stays)},demoMode:false})}
  if(path==='/booking/contract'&&req.method==='GET')return json(res,200,{requestId:id,states:BOOKING_STATES,paymentStates:PAYMENT_STATES,transitions:TRANSITIONS})
  if(path==='/trips'&&req.method==='GET'){const user=await requireUser(req),snap=await db.collection('users').doc(user.uid).collection('travelTrips').orderBy('createdAt','desc').limit(50).get();return json(res,200,{trips:snap.docs.map(d=>({id:d.id,...d.data()}))})}
  if(path.startsWith('/trips/')&&req.method==='GET'){const user=await requireUser(req),tripId=text(path.slice('/trips/'.length),80),snap=await db.collection('users').doc(user.uid).collection('travelTrips').doc(tripId).get();if(!snap.exists)return json(res,404,{code:'trip_not_found',message:'Trip not found.'});return json(res,200,{trip:{id:snap.id,...snap.data()}})}
  if(path==='/airports/search'&&req.method==='GET')return json(res,200,{provider:'OurAirports',keyless:true,results:await keylessAirportSearch(text(req.query?.q,80),{limit:12})});
  if(path==='/flights/search'&&req.method==='POST'){const b=readBody(req),origin=code(b.origin),destination=code(b.destination);if(origin===destination)throw new ProviderError('invalid_request','Origin and destination must differ.',400);const departure=date(b.departure),tripType=b.tripType==='roundtrip'?'roundtrip':'oneway',returnDate=tripType==='roundtrip'?date(b.returnDate):'';if(departure<new Date().toISOString().slice(0,10))throw new ProviderError('invalid_request','Departure date is in the past.',400);if(tripType==='roundtrip'&&returnDate<=departure)throw new ProviderError('invalid_request','Return date must be after departure.',400);const adults=count(b.adults,1,9)||1,children=count(b.children,0,8),ages=Array.isArray(b.childrenAges)?b.childrenAges.map(Number):[];if(ages.length!==children||ages.some(a=>!Number.isInteger(a)||a<2||a>17))throw new ProviderError('child_age_required','Enter a valid age (2–17) for every child before live flight search.',400);return json(res,200,await tryFlights({origin,destination,departure,returnDate,tripType,adults,children,childAges:ages,cabin:cabin(b.cabin),currency:text(b.currency||'PKR',3),region:text(b.region||'PK',8),infants:count(b.infants,0,8)}))}
  if(path==='/flights/offer'&&req.method==='GET'){const d=createFlightProvider();if(!d)throw new ProviderError('provider_unavailable','Duffel offer refresh requires a configured Duffel provider.',503);const offer=await d.getOffer(text(req.query?.id,80));if(!offer)return json(res,404,{code:'offer_not_found',message:'Offer is no longer available.'});return json(res,200,{provider:'Duffel',offer})}
  if(path==='/flights/calendar'&&req.method==='GET'){const input={origin:code(req.query?.origin),destination:code(req.query?.destination),from:date(req.query?.from),tripType:'oneway',returnDate:'',adults:1,children:0,childAges:[],cabin:'economy',currency:String(req.query?.currency||'PKR').slice(0,3),region:'PK'};const p=createFlightApiProvider();if(p){const days=[0,1,2,3,4].map(n=>new Date(`${input.from}T00:00:00Z`).getTime()+n*86400000).map(t=>new Date(t).toISOString().slice(0,10)),calendar=[];for(const d of days){try{const r=await p.searchFlights({...input,departure:d});for(const o of r.results||[])if(o.price!=null)calendar.push({date:d,fare:o.price,currency:o.currency||input.currency,provider:'FlightAPI'});break}catch(e){if(e.code==='provider_auth')break}}return json(res,200,{provider:'FlightAPI',live:true,calendar})}const d=createFlightProvider();if(!d)throw new ProviderError('provider_unavailable','Fare Calendar requires a configured flight provider.',503);return json(res,200,await d.fareCalendar(input))}
  if(path==='/flights/track'&&req.method==='GET'){const p=createFlightApiProvider();if(!p)throw new ProviderError('provider_unavailable','Flight tracking requires a configured status provider.',503);return json(res,200,await p.trackFlight({number:text(req.query?.flight,16).replace(/\s+/g,''),airline:text(req.query?.airline||'',8),date:String(req.query?.date||'').replace(/-/g,''),departureAirport:req.query?.departureAirport}))}
  if(path==='/hotels/search'&&req.method==='POST'){const b=readBody(req),destination=text(b.destination,80),coords=hotelCoords(destination);if(!coords)throw new StaysError('location_unresolved','Hotel search currently supports verified city-centre coordinates for known destinations. Choose a supported city.',400);const p=createDuffelStaysProvider();if(!p)throw new StaysError('provider_unavailable','Duffel Stays is not configured or access has not been granted.',503);const checkIn=date(b.checkIn||b.date),checkOut=date(b.checkOut||b.returnDate);if(checkOut<=checkIn)throw new StaysError('invalid_request','Check-out must be after check-in.',400);return json(res,200,await p.search({latitude:coords.lat,longitude:coords.lng,checkIn,checkOut,guests:count(b.guests,2,20),rooms:count(b.rooms,1,8),radiusKm:count(b.radiusKm,15,50),mobile:Boolean(b.mobile)}))}
  if(path==='/hotels/rates'&&req.method==='GET'){const p=createDuffelStaysProvider();if(!p)throw new StaysError('provider_unavailable','Duffel Stays is not configured.',503);return json(res,200,await p.rates(text(req.query?.id,120)))}
  if(path==='/hotels/quote'&&req.method==='POST'){const p=createDuffelStaysProvider();if(!p)throw new StaysError('provider_unavailable','Duffel Stays is not configured.',503);const b=readBody(req);return json(res,200,await p.quote(text(b.rateId,120)))}
  if(path==='/hotels/book'&&req.method==='POST'){const user=await requireUser(req),p=createDuffelStaysProvider();if(!p)throw new StaysError('provider_unavailable','Duffel Stays is not configured.',503);const b=readBody(req),idem=text(req.get?.('Idempotency-Key')||b.idempotencyKey||'',180);const quoteId=text(b.quoteId,120),attempt=await reserveBookingAttempt(user.uid,idem,quoteId,'Duffel Stays');if(attempt.replay)return json(res,200,{provider:'Duffel Stays',live:true,status:'confirmed',booking:attempt.existing.booking,tripId:attempt.existing.tripId,replayed:true});try{const result=await p.book({...b,idempotencyKey:idem});if(result.status==='confirmed'){const tripId=await recordTrip(user.uid,'Duffel Stays',result.booking);await attempt.ref.set({status:'confirmed',booking:result.booking,tripId,updatedAt:FieldValue.serverTimestamp()},{merge:true});return json(res,200,{...result,tripId})}await attempt.ref.set({status:'unknown',updatedAt:FieldValue.serverTimestamp()},{merge:true});return json(res,200,{...result,status:'unknown'})}catch(e){if(e.code==='booking_unknown')await attempt.ref.set({status:'unknown',updatedAt:FieldValue.serverTimestamp()},{merge:true});else await attempt.ref.set({status:'failed',updatedAt:FieldValue.serverTimestamp()},{merge:true});throw e}}
  if(path==='/buses/search'&&req.method==='POST')return json(res,503,{code:'provider_unavailable',message:'No verified bus inventory provider is configured. No schedules, seats or prices are fabricated.'});
  if(path==='/trains/search'&&req.method==='POST')return json(res,503,{code:'provider_unavailable',message:'No verified rail inventory provider is configured. No schedules, seats or prices are fabricated.'});
  return json(res,404,{code:'not_found',message:'Travel endpoint not found.'});
}catch(e){return handlerError(res,e)}});
