import {NAV,PRIMARY,SUGGESTIONS,RAIL,PROJECT,COMMANDS,DEMO_LOGS} from './data.js';
import {subscribe,getState,executeCommand,advance,pause,resume,stop,retry,setCommand,reset} from './state.js';

const root=document.querySelector('#app');
let route=location.hash.slice(1)||'home';
let drawer=false;
let filter='All';
const icon={home:'⌂',mission:'◎',build:'▣',artifacts:'◇',history:'◷',projects:'▤',selfheal:'⌁',verification:'✓',github:'◈',security:'⚙'};
const labels=Object.fromEntries(NAV);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const status=(state)=>{const map={IDLE:['neutral','Idle'],PLANNING:['info','Planning'],IMPLEMENTING:['info','Implementing'],BUILDING:['info','Building'],TESTING:['info','Testing'],FAILED:['error','Failed'],REPAIRING:['warning','Repairing'],RETESTING:['info','Retesting'],VERIFYING:['warning','Verifying'],VERIFIED:['success','Verified'],DELIVERED:['success','Delivered']};const [tone,text]=map[state]||map.IDLE;return `<span class="status ${tone}"><i></i>${text}</span>`};
function navButton(id){return `<button class="nav-btn ${route===id?'active':''}" data-nav="${id}"><span>${icon[id]||'•'}</span>${labels[id]}</button>`}
function shell(state){return `<div class="workspace"><aside class="sidebar"><div class="brand"><strong>VEYTRIX</strong><span>AUTONOMOUS ENGINEERING CONTROL</span></div><div class="project-chip"><b>${PROJECT.repo}</b><span>${PROJECT.branch}</span></div><div class="nav-group"><div class="nav-label">Control</div>${PRIMARY.map(navButton).join('')}</div><div class="nav-group"><div class="nav-label">Systems</div>${NAV.slice(5).map(navButton).join('')}</div></aside><main class="main"><header class="topbar"><div class="crumb"><strong>${labels[route]||'Home'}</strong><span>${PROJECT.repo} · ${PROJECT.branch}</span></div><div class="top-actions"><button class="btn mobile-menu" data-drawer>MENU</button><button class="btn" data-reset>RESET</button><button class="btn primary" data-run>${state.state==='IDLE'?'RUN':'INSPECT'}</button></div></header><section class="content" id="content">${screen(state)}</section></main></div><nav class="bottom-nav">${PRIMARY.map(id=>`<button class="${route===id?'active':''}" data-nav="${id}"><b>${icon[id]}</b>${labels[id]}</button>`).join('')}</nav>${drawer?drawerMarkup():''}`}
function drawerMarkup(){return `<div class="drawer-backdrop" data-drawer-close></div><aside class="drawer"><div class="brand"><strong>VEYTRIX</strong><span>WORKSPACES</span></div><div class="nav-group">${NAV.map(navButton).join('')}</div></aside>`}
function rail(state){const index=RAIL.findIndex(x=>x.toUpperCase()===state.state.replace('ING','').replace('ED',''));return `<div class="rail">${RAIL.map((name,i)=>{let cls='';if(state.state==='FAILED'&&name==='Test')cls='failed';else if(state.state==='REPAIRING'||state.state==='RETESTING')cls=name==='Repair'?'active':i<4?'done':'';else if(state.state==='VERIFYING')cls=i<5?'done':name==='Verify'?'active':'';else if(state.state==='VERIFIED'||state.state==='DELIVERED')cls=i<6?'done':state.state==='DELIVERED'?'done':'active';else if(index>=0&&i<index)cls='done';else if(index===i)cls='active';return `<div class="rail-node ${cls}"><div class="rail-dot">${i+1}</div><span>${name}</span></div>`}).join('')}</div>`}
function logs(state,limit=8){const items=(state.logs.length?state.logs:DEMO_LOGS).slice(0,limit);return `<div class="logs">${items.map(l=>`<div class="log"><span class="time">${esc(l[0])}</span><span class="kind">${esc(l[1])}</span><span>${esc(l[2])}</span></div>`).join('')}</div>`}
function home(state){return `<div class="screen"><div class="title-row"><div><div class="eyebrow">Command Console</div><h1>Direct the engineering mission.</h1><p>Intent → Plan → Implement → Build → Test → Repair → Verify → Artifact → Deliver</p></div>${status(state.state)}</div><div class="console"><div class="command-row"><input id="command" class="command" value="${esc(state.command)}" placeholder="Type a command… e.g. Build APK" aria-label="Mission command"><button class="btn primary" data-command-run>RUN</button></div><div class="suggestions">${SUGGESTIONS.map(s=>`<button class="suggestion" data-suggest="${esc(s)}">${esc(s)}</button>`).join('')}</div>${rail(state)}</div><div class="grid-2"><section class="panel"><h2>Current Mission</h2><div class="state-line">${status(state.state)}<span class="mono">${state.elapsed}s elapsed</span></div><p style="margin-top:12px">${esc(state.mission)}</p><div class="action-strip"><button class="btn primary" data-advance>Advance stage</button><button class="btn" data-pause>Pause</button><button class="btn" data-resume>Resume</button><button class="btn danger" data-stop>Stop</button></div></section><section class="panel"><h2>Last Result</h2><div class="metric-list"><div class="metric"><span>Repository</span><b>${PROJECT.repo}</b></div><div class="metric"><span>Branch</span><b class="mono">${PROJECT.branch}</b></div><div class="metric"><span>Live GitHub</span><b>${PROJECT.liveConnection?'Connected':'Not connected'}</b></div><div class="metric"><span>Artifact</span><b>${state.artifact?'Evidence supplied':'Not verified'}</b></div></div></section></div><section class="panel"><h2>Execution output</h2>${logs(state)}</section></div>`}
function mission(state){return `<div class="screen"><div class="title-row"><div><div class="eyebrow">Execution Brief</div><h1>Mission Center</h1><p>One execution surface for intent, state, controls and evidence.</p></div>${status(state.state)}</div><div class="two-col"><section class="panel"><h2>Mission</h2><div class="metric-list"><div class="metric"><span>Intent</span><b>${esc(state.mission)}</b></div><div class="metric"><span>Project</span><b>${PROJECT.repo}</b></div><div class="metric"><span>Branch</span><b class="mono">${PROJECT.branch}</b></div><div class="metric"><span>Elapsed</span><b>${state.elapsed}s</b></div></div><div class="action-strip"><button class="btn primary" data-advance>Run / Resume stage</button><button class="btn" data-pause>Pause</button><button class="btn" data-resume>Resume</button><button class="btn" data-stop>Stop</button><button class="btn" data-retry>Retry</button></div></section><section class="panel"><h2>Execution timeline</h2>${rail(state)}</section></div><section class="panel"><h2>Live output</h2>${logs(state,14)}</section></div>`}
function build(state){const stages=[['Build',state.proof.build],['Test',state.proof.test],['Package',false],['Sign',state.proof.sign],['Verify',Object.values(state.proof).every(Boolean)]];return `<div class="screen"><div class="title-row"><div><div class="eyebrow">Engineering Cockpit</div><h1>Build Center</h1><p>Build evidence is never inferred from a UI state.</p></div>${status(state.state)}</div><section class="panel"><div class="three-col"><div><span class="eyebrow">Target</span><b>Android APK</b></div><div><span class="eyebrow">Variant</span><b>Debug / controlled</b></div><div><span class="eyebrow">Environment</span><b>Repository workflow</b></div></div><div class="list" style="margin-top:14px">${stages.map(([n,ok])=>`<div class="list-item"><div><strong>${n}</strong><small>${ok?'Evidence recorded':'Awaiting evidence'}</small></div>${status(ok?'VERIFIED':'IDLE')}</div>`).join('')}</div><div class="action-strip"><button class="btn primary" data-command="Build APK">Start Build</button><button class="btn" data-advance>Advance</button><button class="btn" data-stop>Cancel</button></div></section><section class="panel"><h2>Build logs</h2>${logs(state)}</section></div>`}
function projects(){return `<div class="screen"><div class="title-row"><div><div class="eyebrow">Repository Context</div><h1>Projects</h1><p>List/detail model; no fabricated repository telemetry.</p></div></div><section class="panel"><div class="list"><div class="list-item"><div><strong>${PROJECT.repo}</strong><small>Branch · ${PROJECT.branch}</small></div><span class="status info"><i></i>Configured</span></div></div><div class="action-strip"><button class="btn" data-toast="Branch switching is routed through the repository workflow.">Change Branch</button><button class="btn primary" data-nav="mission">Create Mission</button><a class="btn" href="https://github.com/${PROJECT.repo}/tree/${encodeURIComponent(PROJECT.branch)}" target="_blank" rel="noreferrer">Open GitHub</a></div></section></div>`}
function selfheal(state){const failed=state.state==='FAILED'||state.repairApplied;return `<div class="screen"><div class="title-row"><div><div class="eyebrow">Technical Investigation</div><h1>Self-Healing</h1><p>Diagnosis is separated from verification; applying a repair never means VERIFIED.</p></div>${status(state.state)}</div><div class="two-col"><section class="panel"><h2>What failed?</h2><p>${failed?'TEST · Fixture assertion failure':'No active failure. Start a mission to inspect recovery states.'}</p><h2 style="margin-top:18px">Root signal</h2><p class="mono">ASSERTION_MISMATCH / fixture-output</p><h2 style="margin-top:18px">Diagnosis</h2><p>The demonstration failure indicates an expected-output mismatch. The recovery path isolates the failing stage before proposing a repair.</p></section><section class="panel"><h2>Proposed repair</h2><p>Update the affected implementation and rerun only the impacted verification path.</p><div class="action-strip"><button class="btn primary" data-retry>Apply Repair</button><button class="btn" data-toast="Diff review is available below.">Review Diff</button><button class="btn danger" data-stop>Reject Repair</button></div><h2 style="margin-top:18px">Recovery</h2><p>${state.repairApplied?'Repair Applied → Tests Running → Verification':'Waiting for repair action.'}</p></section></div><section class="panel"><h2>Diff</h2><div class="diff"><span class="minus">- expected: artifact.status = VERIFIED</span>\n<span class="plus">+ actual: artifact.status = EVIDENCE_REQUIRED</span>\n<span class="plus">+ recovery: preserve proof gate until external evidence exists</span></div></section></div>`}
function artifacts(state){return `<div class="screen"><div class="title-row"><div><div class="eyebrow">Artifact Inspector</div><h1>Artifact Center</h1><p>Integrity fields remain empty until a real artifact is supplied.</p></div>${state.artifact?status('VERIFIED'):status('IDLE')}</div><section class="panel"><div class="fingerprint"><div class="eyebrow">ARTIFACT<br>FINGERPRINT</div><div class="hash">${state.artifact?'External evidence supplied':'NO VERIFIED ARTIFACT — SHA-256 unavailable until a real artifact is inspected.'}</div></div><div class="two-col" style="margin-top:14px"><div class="metric-list"><div class="metric"><span>APK name</span><b>${state.artifact?.name||'—'}</b></div><div class="metric"><span>Version</span><b>—</b></div><div class="metric"><span>Build</span><b>—</b></div></div><div class="metric-list"><div class="metric"><span>Signature</span><b>${state.proof.sign?'Verified evidence':'Not verified'}</b></div><div class="metric"><span>Hash</span><b>${state.proof.hash?'Verified evidence':'Not available'}</b></div><div class="metric"><span>Artifact identity</span><b>${state.proof.artifact?'Verified evidence':'Not verified'}</b></div></div></div><div class="action-strip"><button class="btn" data-toast="Download is disabled until a real artifact is connected.">Download APK</button><button class="btn" data-toast="Share is disabled until a real artifact is connected.">Share</button><button class="btn primary" data-nav="verification">Verify Again</button></div></section></div>`}
function history(state){const rows=state.history.filter(x=>filter==='All'||x.result===filter);return `<div class="screen"><div class="title-row"><div><div class="eyebrow">Execution Timeline</div><h1>Run History</h1><p>Only locally recorded execution events are shown.</p></div></div><div class="toolbar">${['All','Delivered','Stopped'].map(x=>`<button class="chip ${filter===x?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div><section class="panel"><div class="list">${rows.length?rows.map(x=>`<div class="list-item"><div><strong>${esc(x.mission)}</strong><small>${new Date(x.time).toLocaleString()} · ${x.duration}s · artifact ${x.artifact?'available':'not available'}</small></div>${status(x.result==='Delivered'?'DELIVERED':'IDLE')}</div>`).join(''):'<div class="empty">No recorded runs yet. Start a command from Home.</div>'}</div></section></div>`}
function verification(state){const names=[['SOURCE','commit / branch context',state.proof.source],['BUILD','build evidence',state.proof.build],['TEST','test result',state.proof.test],['SIGN','signature evidence',state.proof.sign],['HASH','SHA-256 comparison',state.proof.hash],['ARTIFACT','artifact identity',state.proof.artifact]];const verified=names.every(x=>x[2]);return `<div class="screen"><div class="title-row"><div><div class="eyebrow">Trust Chain</div><h1>Verification Proof-Line</h1><p>Only complete evidence can produce VERIFIED.</p></div>${verified?status('VERIFIED'):status('VERIFYING')}</div><section class="panel"><div class="proof">${names.map(([n,d,ok])=>`<div class="proof-item"><b>${ok?'✓':'○'} ${n}</b><span>${d}</span><div style="margin-top:9px">${status(ok?'VERIFIED':'IDLE')}</div></div>`).join('')}</div><div class="action-strip"><button class="btn primary" data-advance>Run Verification</button><button class="btn" data-toast="External evidence must come from a real build/signature/artifact source.">Inspect Evidence</button></div></section><div class="notice ${verified?'':'danger-note'}">${verified?'All required evidence is present.':'VERIFIED is intentionally withheld: one or more required evidence nodes are missing.'}</div></div>`}
function github(){return `<div class="screen"><div class="title-row"><div><div class="eyebrow">Repository Context</div><h1>GitHub</h1><p>Live data is never fabricated. This surface reports connection reality.</p></div><span class="status neutral"><i></i>Not connected</span></div><section class="panel"><div class="metric-list"><div class="metric"><span>Owner / repository</span><b>${PROJECT.repo}</b></div><div class="metric"><span>Branch</span><b class="mono">${PROJECT.branch}</b></div><div class="metric"><span>Commit SHA</span><b class="mono">Available only from live repository context</b></div><div class="metric"><span>PR / CI / changed files</span><b>Not loaded</b></div></div><div class="notice" style="margin-top:14px">VEYTRIX has no live GitHub API session inside this standalone shell. Therefore CI state, PR state, changed files, and live commit telemetry are not represented as facts.</div><div class="action-strip"><a class="btn primary" href="https://github.com/${PROJECT.repo}/tree/${encodeURIComponent(PROJECT.branch)}" target="_blank" rel="noreferrer">View Repository</a><button class="btn" data-toast="Refresh requires a connected GitHub runtime.">Refresh</button><button class="btn" data-toast="Re-authentication requires a connected GitHub runtime.">Re-authenticate</button></div></section></div>`}
function security(){return `<div class="screen"><div class="title-row"><div><div class="eyebrow">Configuration System</div><h1>Security</h1><p>Compact controls for execution safety and verification depth.</p></div></div><section class="settings">${[['GitHub connection','Live repository connector',false],['Safe execution mode','Require explicit recovery action',true],['Self-Healing','Allow controlled repair attempts',true],['Verification depth','Require complete proof-line',true],['Notifications','Surface mission failures',true],['Reduced motion','Respect system preference',false]].map(([a,b,on])=>`<div class="setting"><div><b>${a}</b><span>${b}</span></div><button class="toggle ${on?'on':''}" data-toggle aria-label="Toggle ${a}"></button></div>`).join('')}</section></div>`}
function screen(state){switch(route){case'home':return home(state);case'mission':return mission(state);case'build':return build(state);case'artifacts':return artifacts(state);case'history':return history(state);case'projects':return projects();case'selfheal':return selfheal(state);case'verification':return verification(state);case'github':return github();case'security':return security();default:route='home';return home(state)}}
function render(state){root.innerHTML=shell(state);bind();}
function toast(message){const n=document.createElement('div');n.className='toast';n.textContent=message;document.body.append(n);setTimeout(()=>n.remove(),2200)}
function bind(){
  root.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>{route=b.dataset.nav;drawer=false;history.replaceState(null,'','#'+route);render(getState())}));
  root.querySelectorAll('[data-suggest]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.suggest;setCommand(v);const input=root.querySelector('#command');if(input)input.value=v}));
  root.querySelector('[data-command-run]')?.addEventListener('click',()=>{const v=root.querySelector('#command')?.value||'Build APK';executeCommand(v);render(getState())});
  root.querySelector('[data-run]')?.addEventListener('click',()=>{if(getState().state==='IDLE')executeCommand('Build APK');else advance();render(getState())});
  root.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>{executeCommand(b.dataset.command);render(getState())}));
  root.querySelectorAll('[data-advance]').forEach(b=>b.addEventListener('click',()=>{advance();render(getState())}));
  root.querySelectorAll('[data-pause]').forEach(b=>b.addEventListener('click',()=>{pause();render(getState())}));
  root.querySelectorAll('[data-resume]').forEach(b=>b.addEventListener('click',()=>{resume();render(getState())}));
  root.querySelectorAll('[data-stop]').forEach(b=>b.addEventListener('click',()=>{stop();render(getState())}));
  root.querySelectorAll('[data-retry]').forEach(b=>b.addEventListener('click',()=>{retry();render(getState())}));
  root.querySelector('[data-reset]')?.addEventListener('click',()=>{reset();toast('Execution state reset.');render(getState())});
  root.querySelector('[data-drawer]')?.addEventListener('click',()=>{drawer=true;render(getState())});
  root.querySelector('[data-drawer-close]')?.addEventListener('click',()=>{drawer=false;render(getState())});
  root.querySelectorAll('[data-toast]').forEach(b=>b.addEventListener('click',()=>toast(b.dataset.toast)));
  root.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;render(getState())}));
  root.querySelectorAll('[data-toggle]').forEach(b=>b.addEventListener('click',()=>b.classList.toggle('on')));
  const input=root.querySelector('#command');input?.addEventListener('keydown',e=>{if(e.key==='Enter'){executeCommand(input.value||'Build APK');render(getState())}});
}
subscribe(render);
window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'home';render(getState())});
window.VEYTRIX={getState,executeCommand,advance,reset};
