import fs from 'node:fs';
import { spawn } from 'node:child_process';
const [chromeBinary,driverBinary,serverPort,outDir]=process.argv.slice(2);if(!chromeBinary||!driverBinary||!serverPort||!outDir)throw new Error('Usage: photo-editor-strict-qa.mjs <chrome> <chromedriver> <server-port> <out-dir>');
const port=9526,log=fs.openSync(`${outDir}/chromedriver-photo-strict.log`,'a'),driver=spawn(driverBinary,[`--port=${port}`,'--allowed-ips=127.0.0.1'],{stdio:['ignore',log,log]});let sid='';const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function cmd(method,path,body){const r=await fetch(`http://127.0.0.1:${port}${path}`,{method,headers:body===undefined?undefined:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}),t=await r.text(),j=t?JSON.parse(t):{};if(!r.ok||j?.value?.error)throw new Error(JSON.stringify(j.value||j));return j.value}
async function ex(script,args=[]){return cmd('POST',`/session/${sid}/execute/sync`,{script,args})}async function exa(script,args=[]){return cmd('POST',`/session/${sid}/execute/async`,{script,args})}async function click(s){return ex('const n=document.querySelector(arguments[0]);if(!n)return false;n.click();return true;',[s])}async function wait(script,label,timeout=10000){const st=Date.now();while(Date.now()-st<timeout){if(await ex(script))return;await delay(60)}throw new Error(`Timeout ${label}`)}
const checks=[];function rec(control,pass,evidence=''){checks.push({area:'Photo Adjust v18',control,pass:Boolean(pass),evidence:String(evidence)});if(!pass)console.error(`::error::${control}: ${evidence}`)}async function digest(){return ex('const c=document.querySelector("[data-photo-canvas]");return c&&!c.hidden?c.toDataURL("image/png"):"";')}
async function setRange(s,v){return ex(`const i=document.querySelector(arguments[0]);if(!i)return false;i.focus();i.value=String(arguments[1]);i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new Event('change',{bubbles:true}));i.blur();return true;`,[s,v])}
async function load(){return exa(`const done=arguments[arguments.length-1],i=document.querySelector('[data-photo-file]'),c=document.createElement('canvas');c.width=320;c.height=240;const x=c.getContext('2d');for(let yy=0;yy<240;yy+=8)for(let xx=0;xx<320;xx+=8){x.fillStyle=((xx+yy)/8)%2?'#f4f4f4':'#202020';x.fillRect(xx,yy,8,8)}x.fillStyle='#ee1818';x.fillRect(120,82,70,62);x.fillStyle='#27ae60';x.fillRect(18,150,80,62);x.fillStyle='#1c58d8';x.fillRect(230,20,70,70);c.toBlob(b=>{const dt=new DataTransfer();dt.items.add(new File([b],'strict.png',{type:'image/png'}));i.files=dt.files;i.dispatchEvent(new Event('change',{bubbles:true}));setTimeout(()=>done(true),160)},'image/png');`)}
async function gesture(x1,y1,x2,y2){return ex(`const w=document.querySelector('[data-photo-work]'),c=document.querySelector('[data-photo-canvas]'),r=c.getBoundingClientRect(),old=w.setPointerCapture;w.setPointerCapture=()=>{};const f=(type,x,y)=>w.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:93,pointerType:'touch',clientX:r.left+x*r.width,clientY:r.top+y*r.height,button:0,buttons:type==='pointerup'?0:1}));f('pointerdown',arguments[0],arguments[1]);f('pointermove',arguments[2],arguments[3]);f('pointerup',arguments[2],arguments[3]);w.setPointerCapture=old;return true;`,[x1,y1,x2,y2])}
async function changed(action,label){const before=await ex('return document.querySelector(".nx-photo-editor").dataset.adjustPaint||""');await action();await wait('return (document.querySelector(".nx-photo-editor").dataset.adjustPaint||"")!==arguments[0];'.replace('arguments[0]',JSON.stringify(before)),label,15000);await delay(80)}
async function reset(){await changed(()=>click('[data-photo-reset]'),'reset')}
async function range(sel,value){await changed(()=>setRange(sel,value),sel)}
async function pixel(x,y){return ex('const c=document.querySelector("[data-photo-canvas]");return [...c.getContext("2d").getImageData(Math.floor(c.width*arguments[0]),Math.floor(c.height*arguments[1]),1,1).data]',[x,y])}
async function screenshot(name){const b=await cmd('GET',`/session/${sid}/screenshot`);fs.writeFileSync(`${outDir}/adjust-v18-${name}.png`,Buffer.from(b,'base64'))}
async function loadLarge(){await exa(`const done=arguments[arguments.length-1],c=document.createElement('canvas');c.width=3001;c.height=901;const x=c.getContext('2d');for(let i=0;i<8;i++){x.fillStyle='hsl('+[0,30,60,120,180,240,270,315][i]+',65%,45%)';x.fillRect(i*c.width/8,0,Math.ceil(c.width/8),600)}const g=x.createLinearGradient(0,600,c.width,600);g.addColorStop(0,'#202020');g.addColorStop(1,'#dddddd');x.fillStyle=g;x.fillRect(0,600,c.width,301);c.toBlob(b=>{const dt=new DataTransfer();dt.items.add(new File([b],'adjust-3001.png',{type:'image/png'}));const i=document.querySelector('[data-photo-file]');i.files=dt.files;i.dispatchEvent(new Event('change',{bubbles:true}));done(true)});`);await wait('return document.querySelector("[data-photo-meta]").textContent.includes("3001")&&document.querySelector("[data-photo-canvas]").width>100;','large import');await delay(600)}
try{
 for(let n=0;n<60;n++){try{if((await cmd('GET','/status'))?.ready)break}catch{}await delay(100)}
 for(const [width,height]of [[360,640],[360,740],[393,852],[415,858],[430,865]]){
  const made=await cmd('POST','/session',{capabilities:{alwaysMatch:{browserName:'chrome','goog:chromeOptions':{binary:chromeBinary,args:['--headless=new','--no-sandbox','--disable-dev-shm-usage'],mobileEmulation:{deviceMetrics:{width,height,pixelRatio:1,mobile:true,touch:true}}}}}});sid=made.sessionId;
  await cmd('POST',`/session/${sid}/url`,{url:`http://127.0.0.1:${serverPort}/tools/ai-photo-flagship-qa/harness.html`});await wait('return document.documentElement.dataset.qaReady||document.documentElement.dataset.qaError','harness');
  await ex('return window.__qaRoot.__nxStudioNavigation.openEditor({pick:false});');await wait('return document.querySelector(".nxlock-home")?.hidden===true;','photo editor route');await loadLarge();await click('[data-photo-panel-open="adjust"]');
  rec(`${width}x${height} no page horizontal overflow`,await ex('return document.documentElement.scrollWidth<=innerWidth&&document.querySelector(".nx-photo-editor").scrollWidth<=innerWidth+1'));
  const visible=await ex(`const el=document.querySelector('[data-photo-range="exposure"]'),r=el.getBoundingClientRect(),label=el.closest('.nx-photo-field').querySelector('span'),c=getComputedStyle(label);return {onscreen:r.width>40&&r.top>=0&&r.bottom<=innerHeight,color:c.color,opacity:c.opacity}`);
  rec(`${width}x${height} slider and label visible`,visible.onscreen&&Number(visible.opacity)>.9,JSON.stringify(visible));
  await range('[data-photo-range="exposure"]',.5);await screenshot(`${width}x${height}-light`);
  if(width===360&&height===640){
   await reset();const baseline=await digest();
   for(const[key,value]of Object.entries({exposure:1,contrast:40,highlights:-60,shadows:60,whites:-50,blacks:50,brightness:30,gamma:1.5,temperature:35,tint:35,vibrance:60,saturation:50,rgb:50,red:50,green:50,blue:50})){
    await range(`[data-photo-range="${key}"]`,value);rec(`${key} actual pixel change`,(await digest())!==baseline);await reset();rec(`${key} reset exact baseline`,(await digest())===baseline);
   }
   const orig=await pixel(.4,.85);await range('[data-photo-range="red"]',60);const red=await pixel(.4,.85);rec('Red channel isolation',red[0]>orig[0]&&red[1]===orig[1]&&red[2]===orig[2]);await reset();
   for(const[color,index]of ['red','orange','yellow','green','aqua','blue','purple','magenta'].map((c,i)=>[c,i])){await click('[data-photo-subtab="mix"]');await click(`[data-photo-mix-color="${color}"]`);const own=await pixel((index+.5)/8,.2),far=await pixel(((index+4)%8+.5)/8,.2);await range('[data-photo-mix="h"]',30);const edited=await pixel((index+.5)/8,.2),other=await pixel(((index+4)%8+.5)/8,.2);rec(`${color} HSL targets selected range`,JSON.stringify(own)!==JSON.stringify(edited)&&JSON.stringify(far)===JSON.stringify(other));await reset()}
   await click('[data-photo-subtab="curves"]');
   for(const channel of ['rgb','red','green','blue']){await click(`[data-curve-channel="${channel}"]`);await changed(()=>ex(`const c=document.querySelector('[data-curve-canvas]'),r=c.getBoundingClientRect();c.setPointerCapture=()=>{};for(const[type,y]of [['pointerdown',.5],['pointermove',.2],['pointerup',.2]])c.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:99,clientX:r.left+r.width*.5,clientY:r.top+r.height*y}));return true`),'curve');rec(`${channel} interactive curve changes pixels`,(await digest())!==baseline);await changed(()=>click('[data-curve-reset]'),'curve reset');rec(`${channel} curve reset`,(await digest())===baseline)}
   await click('[data-photo-subtab="histogram"]');await delay(200);const hist=await ex('const c=document.querySelector("[data-photo-histogram]");return {bins:c.__bins,samples:Number(c.dataset.samples)}');rec('Histogram real RGB/luminance pixel totals',hist.samples>100&&hist.bins.length===4&&hist.bins.every(b=>b.reduce((a,v)=>a+v,0)===hist.samples));await range('[data-photo-range="exposure"]',1);await delay(250);rec('Histogram updates with edits',JSON.stringify(hist.bins)!==await ex('return JSON.stringify(document.querySelector("[data-photo-histogram]").__bins)'));await reset();
   const localBaseline=await pixel(.5,.85);await click('[data-adjust-local]');await click('[data-mask-brush="add"]');await changed(()=>gesture(.4,.85,.6,.85),'mask brush');const outside=await pixel(.05,.2);await range('[data-mask-adjust="exposure"]',1);const local=await digest();rec('Local brush affects selected region',JSON.stringify(await pixel(.5,.85))!==JSON.stringify(localBaseline)&&local!==baseline);rec('Local adjustment leaves distant pixels untouched',JSON.stringify(await pixel(.05,.2))===JSON.stringify(outside));await changed(()=>click('[data-photo-undo]'),'local undo');rec('Local adjustment undo restores baseline',(await digest())===baseline);await changed(()=>click('[data-photo-redo]'),'local redo');rec('Local adjustment redo restores pixels',(await digest())===local);await range('[data-mask-strength]',0);rec('Local strength zero is identity',(await digest())===baseline);await reset();
   await click('[data-photo-panel-open="adjust"]');await range('[data-photo-range="gamma"]',1.6);const edit=await digest();await click('[data-copy-edits]');await reset();await changed(()=>click('[data-paste-edits]'),'paste');rec('Copy/paste restores edit',(await digest())===edit);await click('[data-save-preset]');await reset();await changed(()=>click('[data-apply-preset]'),'preset');rec('Saved preset restores edit',(await digest())===edit);await reset();
   await ex(`window.__frames=[];window.__track=true;let last=performance.now();function tick(now){window.__frames.push(now-last);last=now;if(window.__track)requestAnimationFrame(tick)}requestAnimationFrame(tick);`);
   await exa(`const done=arguments[arguments.length-1],i=document.querySelector('[data-photo-range="exposure"]');i.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));let n=0;const timer=setInterval(()=>{i.value=String((n%20)/20);i.dispatchEvent(new Event('input',{bubbles:true}));if(++n===80){clearInterval(timer);i.value='0.7';i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new Event('change',{bubbles:true}));setTimeout(()=>done(true),150)}},8);`);
   const perf=await ex('window.__track=false;return {frames:window.__frames.length,maxGap:Math.max(...window.__frames),value:document.querySelector("[data-photo-range=exposure]").value}');rec('Rapid sliders keep rendering frames and final value',perf.frames>=12&&perf.maxGap<200&&perf.value==='0.7',JSON.stringify(perf));
   await ex(`window.__exportBlobs=[];const original=URL.createObjectURL;URL.createObjectURL=function(blob){if(blob instanceof Blob)window.__exportBlobs.push(blob);return original.call(this,blob)};document.querySelector('[data-photo-format]').value='image/png'`);await click('[data-photo-export]');await wait('return document.querySelector("[data-photo-export-status]").textContent.includes("exported locally at full resolution")','export',30000);const exported=await exa(`const done=arguments[arguments.length-1];createImageBitmap(window.__exportBlobs.at(-1)).then(b=>{const c=document.createElement('canvas');c.width=b.width;c.height=b.height;c.getContext('2d').drawImage(b,0,0);done({width:b.width,height:b.height,pixel:[...c.getContext('2d').getImageData(Math.floor(b.width*.0625),Math.floor(b.height*.2),1,1).data]});})`);rec('Export original resolution',exported.width===3001&&exported.height===901,JSON.stringify(exported));rec('Export contains final committed edit',JSON.stringify(exported.pixel)===JSON.stringify(await pixel(.0625,.2)),JSON.stringify(exported.pixel));
   await click('[data-view-fit]');const fit=await ex('return document.querySelector("[data-photo-canvas]").getBoundingClientRect().width');await click('[data-view-100]');const full=await ex('return document.querySelector("[data-photo-canvas]").getBoundingClientRect().width');rec('100% differs from Fit and shows source pixels',full>fit&&Math.abs(full-3001)<3,JSON.stringify({fit,full}));await click('[data-view-fit]');
  }
  await click('[data-photo-subtab="channels"]');await screenshot(`${width}x${height}-rgb`);await click('[data-photo-sheet-close]');rec(`${width}x${height} close returns canvas`,await ex('return !document.querySelector("[data-photo-sheet]").classList.contains("is-open")'));
  await cmd('DELETE',`/session/${sid}`);sid='';
 }
}catch(e){rec('Execution completed without exception',false,e.stack||e)}finally{if(sid)try{await cmd('DELETE',`/session/${sid}`)}catch{}driver.kill('SIGTERM');const passed=checks.filter(x=>x.pass).length;fs.writeFileSync(`${outDir}/adjust-v18-report.json`,JSON.stringify({passed,total:checks.length,failed:checks.length-passed,checks},null,2));console.log(`Photo Adjust v18: ${passed}/${checks.length}`);if(passed!==checks.length)process.exitCode=1}

// QA gate aligned after v18 sync and visible-route repair.
