import fs from 'node:fs';
import {spawn} from 'node:child_process';

const [chromeBinary,driverBinary,serverPort,outDir]=process.argv.slice(2);
if(!chromeBinary||!driverBinary||!serverPort||!outDir)throw new Error('Usage: batch-v23-qa.mjs <chrome> <chromedriver> <server-port> <out-dir>');
fs.mkdirSync(outDir,{recursive:true});
const port=9540,log=fs.openSync(`${outDir}/chromedriver-batch-v23.log`,'a'),driver=spawn(driverBinary,[`--port=${port}`,'--allowed-ips=127.0.0.1'],{stdio:['ignore',log,log]});
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));let sessionId='',checks=[];
async function command(method,path,body){const response=await fetch(`http://127.0.0.1:${port}${path}`,{method,headers:body===undefined?undefined:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}),raw=await response.text(),json=raw?JSON.parse(raw):{};if(!response.ok||json?.value?.error)throw new Error(`${method} ${path}: ${JSON.stringify(json.value||json)}`);return json.value}
const execute=(script,args=[])=>command('POST',`/session/${sessionId}/execute/sync`,{script,args});
const executeAsync=(script,args=[])=>command('POST',`/session/${sessionId}/execute/async`,{script,args});
async function waitUntil(script,label,timeout=25000){const started=Date.now();while(Date.now()-started<timeout){if(await execute(script))return true;await delay(70)}throw new Error(`Timeout: ${label}`)}
function record(name,pass,evidence=''){checks.push({name,pass:Boolean(pass),evidence:String(evidence)});if(!pass)console.error(`::error::${name}: ${evidence}`)}
async function expect(name,script,args=[]){try{const value=await execute(script,args);record(name,Boolean(value),JSON.stringify(value));return value}catch(error){record(name,false,error?.message||error);return null}}
async function start(){for(let i=0;i<60;i++){try{if((await command('GET','/status'))?.ready)break}catch{}await delay(100)}const made=await command('POST','/session',{capabilities:{alwaysMatch:{browserName:'chrome','goog:chromeOptions':{binary:chromeBinary,args:['--headless=new','--no-sandbox','--disable-dev-shm-usage'],mobileEmulation:{deviceMetrics:{width:393,height:852,pixelRatio:1,mobile:true,touch:true}}}}}});sessionId=made.sessionId;await command('POST',`/session/${sessionId}/timeouts`,{pageLoad:20000,script:30000,implicit:0});await command('POST',`/session/${sessionId}/url`,{url:`http://127.0.0.1:${serverPort}/tools/ai-photo-flagship-qa/harness.html`});await waitUntil('return document.documentElement.dataset.qaReady||document.documentElement.dataset.qaError||"";','harness');const error=await execute('return document.documentElement.dataset.qaError||"";');if(error)throw new Error(error)}
async function injectFixtures(names=['wide.png','tall.png','broken.png']){return executeAsync(`const done=arguments[arguments.length-1],make=(name,w,h,color)=>new Promise(resolve=>{const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const context=canvas.getContext('2d');context.fillStyle=color;context.fillRect(0,0,w,h);canvas.toBlob(blob=>resolve(new File([blob],name,{type:'image/png'})),'image/png')});Promise.all([make(arguments[0],900,450,'rgb(80,140,210)'),make(arguments[1],300,600,'rgb(210,105,75)')]).then(files=>{files.push(new File([new Uint8Array([1,2,3,4,5])],arguments[2],{type:'image/png'}));const transfer=new DataTransfer();files.forEach(file=>transfer.items.add(file));const input=document.querySelector('[data-batch-files]');input.files=transfer.files;input.dispatchEvent(new Event('change',{bubbles:true}));setTimeout(()=>done(files.length),60)}).catch(error=>done({error:String(error)}));`,names)}

try{
  await start();
  await expect('Batch v23 runtime is installed','return !!window.__qaRoot?.__nxBatchV23&&window.__qaRoot.dataset.aiPhotoBatch==="v23-real"&&document.querySelector("[data-batch-files]")?.multiple===true&&!!document.querySelector(".nxbatch-home-launch");');
  await execute('return window.__qaRoot.__nxStudioNavigation.openBatch({reason:"batch-qa"});');await waitUntil('return window.__qaRoot.__nxStudioNavigation.getState().screen==="batch"&&window.__qaRoot.__nxBatchV23.getState().open;','batch route');
  await expect('Canonical router opens the Batch workspace','const s=window.__qaRoot.__nxStudioNavigation.getState();return s.screen==="batch"&&s.batch===true&&!s.home;');
  const injected=await injectFixtures();record('Multi-file input imports one queue',injected===3,String(injected));await waitUntil('return window.__qaRoot.__nxBatchV23.getState().total===3;','three queued files');
  await expect('Every imported file has independent initial status','const s=window.__qaRoot.__nxBatchV23.getState();return s.queued===3&&s.items.every(item=>item.status==="queued"&&item.progress===0);');
  await execute('return window.__qaRoot.__nxBatchV23.setOptions({format:"image/png",maxEdge:512,quality:.92,polish:true});');
  await executeAsync('const done=arguments[arguments.length-1];window.__qaRoot.__nxBatchV23.start().then(done).catch(error=>done({error:String(error)}));');await waitUntil('return !window.__qaRoot.__nxBatchV23.getState().running;','batch complete',30000);
  const completed=await execute('return window.__qaRoot.__nxBatchV23.getState();');
  record('One corrupt file does not stop valid files',completed.ready===2&&completed.failed===1&&completed.processing===0,JSON.stringify(completed));
  record('Resize transform writes real target dimensions',completed.items[0].width===512&&completed.items[0].height===256&&completed.items[1].width===256&&completed.items[1].height===512,JSON.stringify(completed.items.map(item=>({width:item.width,height:item.height,status:item.status}))));
  record('Output format size and filenames are truthful',completed.items.slice(0,2).every((item,index)=>item.outputType==='image/png'&&item.outputSize>100&&item.outputName.endsWith(`-batch-0${index+1}.png`)),JSON.stringify(completed.items.slice(0,2)));
  record('Overall progress reaches terminal state',completed.overallProgress===100&&completed.items.every(item=>item.progress===100),JSON.stringify({overall:completed.overallProgress,progress:completed.items.map(item=>item.progress)}));
  const pixel=await executeAsync(`const done=arguments[arguments.length-1],api=window.__qaRoot.__nxBatchV23,state=api.getState(),result=api.getResult(state.items.find(item=>item.status==='ready').id);createImageBitmap(result.blob).then(bitmap=>{const canvas=document.createElement('canvas');canvas.width=1;canvas.height=1;const context=canvas.getContext('2d');context.drawImage(bitmap,0,0,1,1);const value=[...context.getImageData(0,0,1,1).data];bitmap.close();done(value)}).catch(error=>done({error:String(error)}));`);
  record('Auto polish changes rendered output pixels',Array.isArray(pixel)&&pixel.length===4&&(Math.abs(pixel[0]-80)>2||Math.abs(pixel[1]-140)>2||Math.abs(pixel[2]-210)>2),JSON.stringify(pixel));
  await expect('Queue exposes per-item status and progress','return [...document.querySelectorAll("[data-batch-item]")].length===3&&[...document.querySelectorAll("[data-batch-item] progress")].every(node=>Number(node.value)===100)&&document.querySelectorAll("[data-batch-item][data-status=ready]").length===2&&document.querySelectorAll("[data-batch-item][data-status=failed]").length===1;');
  const downloads=await execute('const before=window.__qaDownloads.length,count=window.__qaRoot.__nxBatchV23.downloadReady(),rows=window.__qaDownloads.slice(before);return {count,rows};');
  record('Download ready exports every successful item only',downloads.count===2&&downloads.rows.length===2&&downloads.rows.every(row=>/-batch-0[12]\.png$/.test(row.download)),JSON.stringify(downloads));
  await execute('const api=window.__qaRoot.__nxBatchV23,s=api.getState(),failed=s.items.find(item=>item.status==="failed");return api.remove(failed.id);');
  await expect('Failed item can be removed independently','const s=window.__qaRoot.__nxBatchV23.getState();return s.total===2&&s.ready===2&&s.failed===0;');
  await execute('return window.__qaRoot.__nxBatchV23.clear();');await injectFixtures(['cancel-a.png','cancel-b.png','cancel-c.png']);
  const cancelled=await executeAsync('const done=arguments[arguments.length-1],api=window.__qaRoot.__nxBatchV23,task=api.start();api.cancel();task.then(()=>done(api.getState())).catch(error=>done({error:String(error)}));');
  record('Cancel isolates and terminates the active queue',cancelled.running===false&&cancelled.ready===0&&cancelled.cancelled===3&&cancelled.items.every(item=>item.status==='cancelled'),JSON.stringify(cancelled));
  await expect('Batch workspace remains phone safe','const w=document.querySelector(".nxbatch-workspace"),r=w.getBoundingClientRect(),buttons=[...w.querySelectorAll(".nxbatch-footer button")].map(b=>b.getBoundingClientRect());return document.documentElement.scrollWidth<=innerWidth+1&&r.left>=-1&&r.right<=innerWidth+1&&r.width<=innerWidth+1&&buttons.every(b=>b.left>=-1&&b.right<=innerWidth+1&&b.height>=34);');
  await command('GET',`/session/${sessionId}/screenshot`).then(png=>fs.writeFileSync(`${outDir}/batch-v23-393x852.png`,Buffer.from(png,'base64')));
  await execute('return window.__qaRoot.__nxStudioNavigation.handleBack({reason:"batch-qa-back"});');await waitUntil('return window.__qaRoot.__nxStudioNavigation.getState().screen==="home";','batch back home');
  await expect('Back returns from Batch to Studio Home','const s=window.__qaRoot.__nxStudioNavigation.getState();return s.home===true&&s.batch===false&&!window.__qaRoot.__nxBatchV23.getState().open;');
}catch(error){record('Uncaught Batch v23 QA',false,error?.stack||error)}finally{if(sessionId)try{await command('DELETE',`/session/${sessionId}`)}catch{}driver.kill('SIGTERM');fs.closeSync(log)}
const failed=checks.filter(check=>!check.pass);fs.writeFileSync(`${outDir}/batch-v23-report.json`,JSON.stringify({generatedAt:new Date().toISOString(),viewport:{width:393,height:852},summary:{total:checks.length,passed:checks.length-failed.length,failed:failed.length},checks},null,2));
if(failed.length){console.error(`Batch v23 QA FAIL — ${failed.length}/${checks.length}`);process.exit(1)}console.log(`Batch v23 QA PASS — ${checks.length} checks passed.`);
