import fs from 'node:fs';
import { spawn } from 'node:child_process';
const [chromeBinary,driverBinary,serverPort,outDir]=process.argv.slice(2);if(!chromeBinary||!driverBinary||!serverPort||!outDir)throw new Error('Usage: photo-ai-qa.mjs <chrome> <chromedriver> <server-port> <out-dir>');
const port=9520,log=fs.openSync(`${outDir}/chromedriver-photo-ai.log`,'a'),driver=spawn(driverBinary,[`--port=${port}`,'--allowed-ips=127.0.0.1'],{stdio:['ignore',log,log]});let sid='';const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function cmd(method,path,body){const r=await fetch(`http://127.0.0.1:${port}${path}`,{method,headers:body===undefined?undefined:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}),t=await r.text(),j=t?JSON.parse(t):{};if(!r.ok||j?.value?.error)throw new Error(JSON.stringify(j.value||j));return j.value}async function ex(s,a=[]){return cmd('POST',`/session/${sid}/execute/sync`,{script:s,args:a})}async function exa(s,a=[]){return cmd('POST',`/session/${sid}/execute/async`,{script:s,args:a})}async function click(s){return ex('const n=document.querySelector(arguments[0]);if(!n)return false;n.click();return true;',[s])}async function wait(s,label,timeout=12000){const st=Date.now();while(Date.now()-st<timeout){if(await ex(s))return;await delay(60)}throw new Error(`Timeout ${label}`)}async function digest(){return ex('const c=document.querySelector("[data-photo-canvas]");return c&&!c.hidden?c.toDataURL("image/png"):"";')}
const checks=[];function rec(control,pass,evidence=''){checks.push({area:'Photo AI',control,pass:Boolean(pass),evidence:String(evidence)});if(!pass)console.error(`::error::Photo AI — ${control}: ${evidence}`)}
async function load(){return exa(`const done=arguments[arguments.length-1],i=document.querySelector('[data-photo-file]'),c=document.createElement('canvas');c.width=280;c.height=210;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,280,210);g.addColorStop(0,'#26164c');g.addColorStop(.45,'#b85c43');g.addColorStop(1,'#3d8dbd');x.fillStyle=g;x.fillRect(0,0,280,210);x.fillStyle='#f4d7be';x.fillRect(82,35,118,128);x.fillStyle='#222';x.fillRect(108,74,18,9);x.fillRect(158,74,18,9);x.fillStyle='#d65a55';x.fillRect(126,126,34,8);c.toBlob(b=>{const dt=new DataTransfer();dt.items.add(new File([b],'ai-qa.png',{type:'image/png'}));i.files=dt.files;i.dispatchEvent(new Event('change',{bubbles:true}));setTimeout(()=>done(true),170)},'image/png');`)}
function writeReport(extra={}){const passed=checks.filter(c=>c.pass).length,failed=checks.length-passed,payload={total:checks.length,passed,failed,checks,...extra};fs.writeFileSync(`${outDir}/photo-ai-report.json`,JSON.stringify(payload,null,2));fs.writeFileSync(`${outDir}/photo-ai-report.md`,`# Photo AI execution QA (local stub; no paid call)\n\n- Final visible contract: six AI edit actions only; legacy Analyze/prompt/Copy row is intentionally removed by phone-feedback layer.\n- Total: ${checks.length}\n- Passed: ${passed}\n- Failed: ${failed}\n${extra.error?`- Fatal: ${extra.error}\n`:''}\n${checks.map(c=>`- ${c.pass?'PASS':'FAIL'} — ${c.control}: ${c.evidence}`).join('\n')}\n`);return{passed,failed}}
try{for(let n=0;n<60;n++){try{if((await cmd('GET','/status'))?.ready)break}catch{}await delay(100)}const made=await cmd('POST','/session',{capabilities:{alwaysMatch:{browserName:'chrome','goog:chromeOptions':{binary:chromeBinary,args:['--headless=new','--no-sandbox','--disable-dev-shm-usage'],mobileEmulation:{deviceMetrics:{width:393,height:852,pixelRatio:1,mobile:true,touch:true}}}}}});sid=made.sessionId;await cmd('POST',`/session/${sid}/url`,{url:`http://127.0.0.1:${serverPort}/tools/ai-photo-flagship-qa/harness.html`});await wait('return document.documentElement.dataset.qaReady||document.documentElement.dataset.qaError||"";','harness',20000);const error=await ex('return document.documentElement.dataset.qaError||"";');if(error)throw new Error(error);await load();await wait('return !document.querySelector("[data-photo-canvas]").hidden;','image');await click('[data-photo-panel-open="ai"]');await wait('return document.querySelector("[data-photo-sheet-panel=ai]").classList.contains("is-active");','AI panel');rec('Final AI panel exposes exactly six visible edit actions',await ex('return document.querySelectorAll("[data-photo-sheet-panel=ai] [data-photo-ai]").length===6&&!document.querySelector("[data-photo-prompt]")&&!document.querySelector("[data-photo-analyze]")&&!document.querySelector("[data-photo-copy]");'),'six-action quick-only contract');
  for(const mode of ['auto','relight','color','portrait','denoise','detail']){await click('[data-photo-reset]');await delay(100);const before=await digest(),calls=await ex('return window.__qaFirebaseAiCalls.length;');const busy=await ex(`const b=document.querySelector('[data-photo-ai="${mode}"]');b.click();return /analyzing/i.test(document.querySelector('[data-photo-ai-status]').textContent);`);rec(`${mode} shows busy state`,busy,'status');await wait(`return /${mode} applied in-app\./i.test(document.querySelector('[data-photo-ai-status]').textContent);`,`${mode} completion`);const afterCalls=await ex('return window.__qaFirebaseAiCalls.length;'),after=await digest();rec(`${mode} one tap makes exactly one AI call`,afterCalls===calls+1,`delta=${afterCalls-calls}`);rec(`${mode} applies a visible in-app edit`,after!==before,'render digest');if(mode==='auto'){await click('[data-photo-undo]');await delay(110);rec('AI edit supports Undo',(await digest())!==after,'undo digest')}}
  await click('[data-photo-reset]');await ex('window.__qaFirebaseAiFail=true;return true;');const failCalls=await ex('return window.__qaFirebaseAiCalls.length;');await click('[data-photo-ai="auto"]');await wait('return /forced failure/i.test(document.querySelector("[data-photo-ai-status]").textContent);','AI failure');rec('AI action exposes explicit failure state',true,'forced local-stub error visible');rec('Failed AI action still makes only one intended call',(await ex('return window.__qaFirebaseAiCalls.length;'))===failCalls+1,'call delta');await ex('window.__qaFirebaseAiFail=false;return true;');
  const {passed,failed}=writeReport();console.log(`Photo AI QA: ${passed}/${checks.length}`);if(failed)process.exitCode=1;
}catch(e){const message=String(e?.stack||e);writeReport({error:message});console.error(message);process.exitCode=1}finally{if(sid)try{await cmd('DELETE',`/session/${sid}`)}catch{}driver.kill('SIGTERM')}
